# Generated by Django 4.1.3 on 2022-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topper', '0002_insertsymbols_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertsymbols',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
