# Generated by Django 4.1.3 on 2022-11-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topper', '0003_insertsymbols_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertsymbols',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
